packages:
  - apps/*
  - libs/*

allowBuilds:
  esbuild: true

catalog:
  "@types/node": ^25.9.1
  "@typescript/native-preview": 7.0.0-dev.20260604.1
  tsdown: ^0.22.2

catalogs:
  oxc:
    oxfmt: ^0.53.0
    oxlint: ^1.68.0
    oxlint-tsgolint: ^0.23.0
