packages:
  - apps/*
  - libs/*

allowBuilds:
  esbuild: true

catalog:
  "@types/node": ^26.1.0
  tsdown: ^0.22.3
  typescript: 7.0.1-rc

catalogs:
  oxc:
    oxfmt: ^0.57.0
    oxlint: ^1.72.0
    oxlint-tsgolint: ^0.24.0
