packages:
  - apps/*
  - libs/*

allowBuilds:
  esbuild: true

catalog:
  "@types/node": ^26.1.1
  tsdown: ^0.22.8
  typescript: 7.0.2

catalogs:
  oxc:
    oxfmt: ^0.59.0
    oxlint: ^1.74.0
    oxlint-tsgolint: ^0.24.0
